# Generated by Django 5.2.8 on 2025-11-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_featureprice_feature_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.DeleteModel(
            name='FeaturePrice',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
