# Generated by Django 3.2 on 2025-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_wallet_user_remove_plan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='DownloadPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'student'), ('doctor', 'doctor'), ('other', 'other')], max_length=20)),
                ('file_type', models.CharField(choices=[('image', 'image'), ('pdf', 'pdf'), ('csv', 'csv')], max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('role', 'file_type')},
            },
        ),
    ]
