# Generated by Django 5.2.8 on 2025-11-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_wallet_user_remove_plan_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor'), ('other', 'Other')], max_length=20)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('csv', 'CSV')], max_length=20)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'unique_together': {('role', 'file_type')},
            },
        ),
    ]
