# Generated by Django 5.2.8 on 2025-11-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_downloadprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadprice',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('pdf', 'pdf'), ('csv', 'csv')], max_length=20),
        ),
        migrations.AlterField(
            model_name='downloadprice',
            name='role',
            field=models.CharField(choices=[('student', 'student'), ('doctor', 'doctor'), ('other', 'other')], max_length=20),
        ),
    ]
