# Generated by Django 5.2.8 on 2025-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_auto_20251125_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadprice',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('pdf', 'pdf'), ('csv', 'csv'), ('zip', 'zip')], max_length=20),
        ),
    ]
