# Generated by Django 5.2.8 on 2025-12-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_mongouser_wallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
