# Generated by Django 5.2.8 on 2025-11-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(max_length=50)),
                ('package', models.CharField(max_length=50)),
                ('plan', models.CharField(default='-', max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
